name: Folder Sorter CI

on:
  push:
  pull_request:

jobs:
  build-and-test:

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Build backend (Linux)
      if: runner.os == 'Linux'
      run: |
        cd backend
        make

    - name: Build backend (Windows)
      if: runner.os == 'Windows'
      run: |
        cd backend
        build.bat

    - name: Run tests
      run: |
        pytest tests
